# Generated by Django 3.2.7 on 2021-10-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_collection',
            field=models.CharField(choices=[('LR', 'LivingRoom'), ('BR', 'BedRoom'), ('K', 'Kitchen')], default='LR', max_length=2),
        ),
    ]
