# Generated by Django 3.2.7 on 2021-10-08 06:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_collection',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('K', 'Kitchen'), ('BR', 'BedRoom'), ('LR', 'LivingRoom')], max_length=7),
        ),
    ]
