# Generated by Django 3.2.7 on 2021-10-23 08:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_collection',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('LR', 'LivingRoom'), ('K', 'Kitchen'), ('BR', 'BedRoom')], max_length=7),
        ),
    ]
