# Generated by Django 3.2.7 on 2021-10-23 09:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_collection',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BR', 'BedRoom'), ('NA', 'New-Arrivals'), ('LR', 'LivingRoom'), ('K', 'Kitchen')], max_length=10),
        ),
    ]
