# Generated by Django 3.2.7 on 2021-10-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='f_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='l_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
    ]
