# Generated by Django 3.2.7 on 2021-10-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211011_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='state',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zipcode',
            field=models.CharField(max_length=200),
        ),
    ]
