# Generated by Django 3.2.7 on 2021-10-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20211011_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='cart',
        ),
    ]
